services:
  - type: web
    name: ai-agent-platform
    runtime: docker
    plan: free
    # Use the root-level Dockerfile
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NODE_VERSION
        value: 20.11.0
    healthCheckPath: /health 