services:
  - type: web
    name: ai-agent-backend
    runtime: node
    plan: free
    # Specify Node.js 20+ for Vite compatibility
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NODE_VERSION
        value: 20.11.0
    healthCheckPath: /health 